### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by sevastos**
Some minor random fixes found during setup

### CODE REVIEW

**Comment by Marak** [comment]
Thanks!

**Comment by sevastos** [comment]
Cheers :)

**Comment by Marak** [comment]
Let me know if there is a particular area you are interested in contributing to, I would be glad to provide guidance or answer any questions.

**Comment by sevastos** [comment]
Did another small PR :). Well I'm full-stack, although mainly working with front-end lately. If you have any available tasks that could wait a bit maybe you could create issues and tag them for beginners like me to jump on.

My main problem right now is figuring out the couchdb setup.

**Comment by Marak** [comment]
I took a look at your other PR and it looks good. Made some comments.

If you need a couch you should be able to get one instantly using
http://www.iriscouch.com/

I haven't created any Github issues yet, but there is a TODO file
https://github.com/bigcompany/safewallet/blob/master/TODO

Most of those items are non-critical. I would suggest continuing to dig
through the code we have looking for any potential problems or security
concerns. Improving UI / UX would also be great.

I'm currently traveling but will be back online late tomorrow. I'll try to
prioritize the development pipeline and create Github issues when I get
back.

**Pull request merged**
